// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOLQ4TpC_uxXCydHWiMoVfUwCSnWWNZmw',
    appId: '1:748494867884:web:0b3e372edec880d96dbe09',
    messagingSenderId: '748494867884',
    projectId: 'campus-pulse',
    authDomain: 'campus-pulse.firebaseapp.com',
    storageBucket: 'campus-pulse.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZG_WZz39qG8V7xtnivVC9Sw0BiiNAyQ0',
    appId: '1:748494867884:android:4d0856d787f6e4586dbe09',
    messagingSenderId: '748494867884',
    projectId: 'campus-pulse',
    storageBucket: 'campus-pulse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX5G58Xjwj8u35xl8jQHx9wd_2Js2wlDw',
    appId: '1:748494867884:ios:dd77ea5d07dc5a1d6dbe09',
    messagingSenderId: '748494867884',
    projectId: 'campus-pulse',
    storageBucket: 'campus-pulse.appspot.com',
    iosClientId: '748494867884-b72de8fdea78mho15dh3ourvbn40ha3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCompleteGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX5G58Xjwj8u35xl8jQHx9wd_2Js2wlDw',
    appId: '1:748494867884:ios:dd77ea5d07dc5a1d6dbe09',
    messagingSenderId: '748494867884',
    projectId: 'campus-pulse',
    storageBucket: 'campus-pulse.appspot.com',
    iosClientId: '748494867884-b72de8fdea78mho15dh3ourvbn40ha3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCompleteGuide',
  );
}
